config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :kitten
  root "kitten#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kitten_controller.rb
class KittenController < ApplicationController

    def index
        @kitten = Kitten.all
        
        respond_to do |format|
            format.html # index.html.erb
            format.json { render :json => @kittens }
        end
    end

    def show
        @k = Kitten.find(params[:id])

        respond_to do |format|
            format.html
            format.json { render :json => @kitten }
        end
    end

    def new
        @kitten = Kitten.new
    end

    def create
        @kitten = Kitten.new(kitten_params) 
        if @kitten.save
            flash.alert = "You saved!"
            redirect_to @kitten
        else
            flash.alert = "Failed"
        end
    end

    def edit
        @kitten = Kitten.find(params[:id])
    end

    def update
        @kitten = Kitten.find(params[:id])

        if @kitten.update(kitten_params)
          flash[:success] = "Your kitten has been updated!"
          redirect_to @kitten
        else
          flash.now[:error] = "The kitten couldn't be updated, please fix your errors."
          render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @kitten = Kitten.find(params[:id])
        @kitten.destroy

        flash[:notice] = "Your kitten has been deleted."
        redirect_to root_path, status: :see_other
    end
    
    private
        def kitten_params
            params.require(:kitten).permit(:name, :age, :cuteness, :softness)
        end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kitten_helper.rb
module KittenHelper
end

app/views/kitten/edit.html.erb
<%= form_with model: @kitten do |f| %>
    <%= f.label "name"%> <br>
    <%= f.text_field :name%> <br>
    <%= f.label "age"%> <br>
    <%= f.text_field :age%> <br>
    <%= f.label "cuteness"%> <br>
    <%= f.text_field :cuteness%> <br>
    <%= f.label "softness"%> <br>
    <%= f.text_field :softness%> <br>
    <%= f.submit%>
<% end %>

app/views/kitten/index.html.erb
<h1> This is your cat Information </h1>

<% @kitten.each do |k| %>
    <h2><%= link_to k.name, k%></h2>
<% end %>


<h2><%= link_to "Create New Kitten", new_kitten_path %>

app/views/kitten/new.html.erb
<%= form_with model: @kitten, url: "/kitten" do |f| %>
    <%= f.label "name"%> <br>
    <%= f.text_field :name%> <br>
    <%= f.label "age"%> <br>
    <%= f.text_field :age%> <br>
    <%= f.label "cuteness"%> <br>
    <%= f.text_field :cuteness%> <br>
    <%= f.label "softness"%> <br>
    <%= f.text_field :softness%> <br>
    <%= f.submit%>
<% end %>

app/views/kitten/show.html.erb
<h2>Name of the cat: <%= @k.name %></h2>
<h2>Age of the cat: <%= @k.age %></h2>
<h2>Cuteness of the cat: <%= @k.cuteness %></h2>
<h2>Softness of the cat: : <%= @k.softness %></h2>

<%= link_to 'Back', root_path%>
<%= link_to 'Edit' , edit_kitten_path%>
<%= link_to "Delete", kitten_path(params[:id]),
      data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>